version: '3'
services:
  wg:
    container_name: wireguard
    image: linuxserver/wireguard
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - SERVERURL=wg.ataran.me
      - PEERS=laptop,tablet,phone
      - PEERDNS=auto
      - SERVERPORT=5182
    volumes:
      - "/home/atrn0/wireguard_config:/config"
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - "5182:51820/udp"
    networks:
      wg6:
networks:
  wg6:
    external: true
